version: '3.5'

services:
  d-proxy:
    restart: unless-stopped 
    image: ${PREFIX}${LABEL}_${NAME}
    container_name: ${PREFIX}${LABEL}_${NAME}
    hostname: ${PREFIX}${LABEL}_${NAME}
    environment:
        - STAGE=${STAGE}
        - PREFIX=${PREFIX}
        - LABEL=${LABEL}
        - NAME=${NAME}
        - TILDA=/usr/nodejs/tilda/
        - SDA=/usr/nodejs/sda/
        - AFTER_TILDA=${AFTER_TILDA}
        - EXTRA=${EXTRA}
    ports:
      - "80:80"
      - "443:443"
      - "43111:43111"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - tilda
    volumes:
      - ~/:/usr/nodejs/tilda/
      - /mnt/sda:/usr/nodejs/sda/
      - ~/.config/letsencrypt/certs/:/usr/nodejs/le

networks:
  tilda:
    external:
      name: tilda