version: '3.5'

services:
  d-listener:
    restart: unless-stopped
    image: ${PREFIX}${LABEL}_${NAME}
    container_name: ${PREFIX}${LABEL}_${NAME}
    hostname: ${PREFIX}${LABEL}_${NAME}
    environment:
        - STAGE=${STAGE}
        - PREFIX=${PREFIX}
        - LABEL=${LABEL}
        - NAME=${NAME}
        - TILDA=/usr/nodejs/tilda/
        - AFTER_TILDA=${AFTER_TILDA}
        - EXTRA=${EXTRA}
    ports:
      - "${PORT1}:80"
      - "${PORT2}:443"
    networks:
      - tilda
    volumes:
      - ~/:/usr/nodejs/tilda/
      - /mnt/sda:/usr/nodejs/sda/
      - ~/.config/letsencrypt/certs/:/usr/nodejs/le

networks:
  tilda:
    external:
      name: tilda